// <auto-generated />
using System;
using Ecom.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecom.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250309121513_ProductPictureProperty")]
    partial class ProductPictureProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecom.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bf54ecd-e88b-469b-8f35-fb3e942e208e"),
                            Description = "Electronic Items",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("fc4e00f1-b435-4aac-8663-87a5ad2920e8"),
                            Description = "Clothing Items",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("601542f2-78d1-4451-a54d-fc213b3c95c4"),
                            Description = "Grocery Items",
                            Name = "Grocery"
                        });
                });

            modelBuilder.Entity("Ecom.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0cb15aa5-6f0a-4622-9ca6-8aab9fe2a669"),
                            CategoryId = new Guid("5bf54ecd-e88b-469b-8f35-fb3e942e208e"),
                            Description = "Laptop",
                            Name = "Laptop",
                            Price = 1000m
                        },
                        new
                        {
                            Id = new Guid("2f09e29d-3e8d-4803-8f05-2292c31bfcbf"),
                            CategoryId = new Guid("fc4e00f1-b435-4aac-8663-87a5ad2920e8"),
                            Description = "T-Shirt",
                            Name = "T-Shirt",
                            Price = 20m
                        },
                        new
                        {
                            Id = new Guid("b8058830-6986-4b6a-8741-353238f889b0"),
                            CategoryId = new Guid("601542f2-78d1-4451-a54d-fc213b3c95c4"),
                            Description = "Rice",
                            Name = "Rice",
                            Price = 10m
                        },
                        new
                        {
                            Id = new Guid("906a08df-dc68-4383-9703-14a81fce3041"),
                            CategoryId = new Guid("5bf54ecd-e88b-469b-8f35-fb3e942e208e"),
                            Description = "Mobile",
                            Name = "Mobile",
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("80eba83e-25c3-4f5a-87ef-f93b09b94de6"),
                            CategoryId = new Guid("fc4e00f1-b435-4aac-8663-87a5ad2920e8"),
                            Description = "Jeans",
                            Name = "Jeans",
                            Price = 50m
                        });
                });

            modelBuilder.Entity("Ecom.Core.Entities.Product", b =>
                {
                    b.HasOne("Ecom.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecom.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
